/**
 * Public share tokens for the parent report.
 *
 * The token lives in `assessment_participants.share_token`: 16 random bytes as
 * 22 base64url characters, generated by `public.generate_share_token()`. It is
 * a value of its own rather than a packed row id, so a leaked link can be
 * rotated or revoked (`share_revoked_at`) without touching the participant.
 *
 * Nothing here decodes anything — the token is only matched against the column.
 * This module just guards the URL shape so obvious junk never reaches Supabase.
 */

const SHARE_TOKEN_PATTERN = /^[A-Za-z0-9_-]{22}$/;

export function isShareToken(value: string): boolean {
  return SHARE_TOKEN_PATTERN.test(value.trim());
}

/** Returns the trimmed token, or null when it cannot be one. */
export function normalizeShareToken(value: string): string | null {
  const token = value.trim();

  return isShareToken(token) ? token : null;
}

export function getParentReportHref(shareToken: string): string {
  return `/parent/${shareToken}`;
}
